### ISSUE TITLE
Missing search & replace context menus

### ISSUE THREAD

**Issue by jerzyk** [trinhanhngoc/pycharm-odoo#400] opened 2023-07-19 06:41 UTC
v2023.7.0.232 adds stubs and hides them in the project view - unfortunately as a side effect - options to search & replace are gone:
<img width="269" alt="Screenshot 2023-07-19 at 08 31 29" src="https://github.com/odoo-ide/pycharm-odoo/assets/199073/0d55a49b-3a27-412c-91b6-7c44d5923837">

with "old" option clicking on whole project will not show this, but clicking on content root of the code shows it:

<img width="443" alt="Screenshot 2023-07-19 at 08 35 46" src="https://github.com/odoo-ide/pycharm-odoo/assets/199073/4abf9383-aa14-4c40-bdb2-f4ca3747cd4e">

**Comment by trinhanhngoc** [comment] 2023-07-19 07:06
Hi @jerzyk. Although the Find and Replace context menus are not displayed, their keyboard shortcuts still work. This seems to be an issue of PyCharm itself.

**Comment by jerzyk** [comment] 2023-07-19 10:38
unfortunatelly, keyboard shortcuts do not work either - because search dialog is trying to use stubs directory as a base for searches (e.g. /Users/jerzyk/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-1/232.8660.49/PyCharm 2023.2 EAP.app.plugins/Odoo/stubs/odoo-stubs14)

**Comment by trinhanhngoc** [comment] 2023-07-19 10:45
> unfortunatelly, keyboard shortcuts do not work either - because search dialog is trying to use stubs directory as a base for searches (e.g. /Users/jerzyk/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-1/232.8660.49/PyCharm 2023.2 EAP.app.plugins/Odoo/stubs/odoo-stubs14)

Oh, you're right. Let me find a solution to this problem.

**Comment by trinhanhngoc** [comment] 2023-07-24 14:09
Hi @jerzyk . The new version 2023.7.1 has been released with the improvement for **Find/Replace in Files...** actions. When running these actions (via keyboard shortcuts), the hidden odoo-stubs will not be used as the default directory for searching.

**Closed as completed by trinhanhngoc** 2023-07-24 14:09 UTC
Labels: addressed in next version

**Comment by boom-solutions** [comment] 2023-07-29 23:16
> Hi @jerzyk . The new version 2023.7.1 has been released with the improvement for **Find/Replace in Files...** actions. When running these actions (via keyboard shortcuts), the hidden odoo-stubs will not be used as the default directory for searching.

I still have big problem with shortcut keys in macOS

**Comment by trinhanhngoc** [comment] 2023-07-30 02:59
> > Hi @jerzyk . The new version 2023.7.1 has been released with the improvement for **Find/Replace in Files...** actions. When running these actions (via keyboard shortcuts), the hidden odoo-stubs will not be used as the default directory for searching.
> 
> I still have big problem with shortcut keys in macOS

Hello @boom-solutions . Is your problem similar to the one stated here, or is it another problem related to keyboard shortcuts?

**Comment by boom-solutions** [comment] 2023-07-30 14:11
the same problem, but in the shortcut, I faced big problems and lost so much code with only one (control+z)
copy and paste is not working too, and I do not know when happened, but after spending some time in Pycharm, I faced the problem, the plugin is very nice, but this problem is so dangers.

**Comment by trinhanhngoc** [comment] 2023-07-30 14:17
> the same problem, but in the shortcut, I faced big problems and lost so much code with only one (control+z)
> copy and paste is not working too, and I do not know when happened, but after spending some time in Pycharm, I faced the problem, the plugin is very nice, but this problem is so dangers.

Can you provide steps to reproduce the problem so I can test it?

**Comment by boom-solutions** [comment] 2023-07-31 07:55
really I still can not answer, but what I do now, 
I removed all plugins and just installed your plugin, and I will see, 
now 2nd day nothing happened. 
I have doubts, maybe come from another suggested plugin you mentioned in your documents,
or maybe comes from PyDev.Debugger.
but I believe, after installing your plugin and other related, the problem come.
