### ISSUE TITLE
Slow model name completion

### ISSUE THREAD

**Issue by hra0123** [trinhanhngoc/pycharm-odoo#508] opened 2024-11-13 06:24 UTC
previous version it was working fine , 
for example
adding new many2one field after type res it shows  the full option there like res.partner, res.users, res.company etc 
partner_id = fields.Many2one('res.partner')

now i am using the latest version pycharm-odoo , it does not showing options . need to type full name like res.partner , res.users 
i am not remembering which version it was correct . after some update the of this package the option not showing

**Comment by trinhanhngoc** [comment] 2024-11-13 07:59
Hello @hra0123 ,

The latest version is 2024.9.1. I just checked again, everything is still working fine.

<img width="1511" alt="image" src="https://github.com/user-attachments/assets/46d24a89-c9be-4752-b6f6-b9fcef124b5a">

Can you help me check if the issue also occurs with files in the Odoo source code (eg `addons/account/models/account_account.py`)?

**Comment by hra0123** [comment] 2024-11-13 11:25
i am also using latest version 2024.9.1.242 this one . 
i checked on default addons and custom modules . same like that . 
not listing 
i am using  PyCharm 2024.2.4 (Community Edition) and ubuntu os . 
any idea why the values not listing in my case ? 
i checked in previous version of pycharm but same issue still exists .

**Comment by trinhanhngoc** [comment] 2024-11-14 09:17
@hra0123 ,

How do you structure your project in PyCharm?

**Comment by hra0123** [comment] 2024-11-14 10:55
structure is same like yours 
/home/ubuntu/odoo-dev/SEVENTEEN/odoo-bin
like this . 

before i think i installed this package pydevd-odoo, that cause issue , but that is not problem . i unistall pydev-odoo package then the issue still exists . 

in _inherit also it does not listing . 

other parts are working fine . i face the problem with these 2 cases. 

i test several  cases and i found the listing values takes too much time to populate . _inherit case and relation fields case it takes time . now it's listing . could you know the reason for the slowness issue ?

**Comment by trinhanhngoc** [comment] 2024-11-15 07:58
@hra0123 ,

I just also noticed model name completion in PyCharm 2024.3 is slower. I will investigate this further.

**Comment by trinhanhngoc** [comment] 2024-11-18 10:04
@hra0123 ,

I just found the root cause of the problem. This will be fixed in the next version this week.

**Comment by trinhanhngoc** [comment] 2024-11-20 03:03
Hello @hra0123 ,

The new version 2024.9.3 has been released to address this issue.

**Closed as completed by trinhanhngoc** 2024-11-20 03:03 UTC
Labels: addressed in next version, performance
