### ISSUE TITLE
Tab name displaying full file path instead of just file name.

### ISSUE THREAD

**Issue by PierrePasq** [trinhanhngoc/pycharm-odoo#480] opened 2024-08-19 13:23 UTC
Since the last update, I have an issue with the tab name displaying the full path of the file (ProjectName Path/to/myfile.py) instead of just the file name (myfile.py). 
I have tried to disable the "Show directory for non-unique file names" option for pycharm Editor Tabs and it stays the same.

What it looks like:
![image](https://github.com/user-attachments/assets/56499d85-444a-4ef4-89c2-63d0ea323b2b)

What it should look like:
![image](https://github.com/user-attachments/assets/a337e365-65ec-4e56-881a-a08a93f35d23)

As you see, it takes a lot more unnecessary space. I only get the correct display when I entirely disable the plugin.

**Comment by trinhanhngoc** [comment] 2024-08-19 14:04
Hello @PierrePasq,

What version of PyCharm and Odoo plugin are you using?

**Comment by PierrePasq** [comment] 2024-08-19 14:12
Hello @trinhanhngoc ,

I am using PyCharm Professional "Build #PY-242.20224.347, built on August 9, 2024". 
Odoo plugin is version 2024.6.1.242. 
I only have the Odoo plugin with XpathView (latest version). 
I should add that when I launch pycharm, the tabs are correctly named for a split-second, and then they get the full path as name.
Maybe the problem is within my project architecture:

![image](https://github.com/user-attachments/assets/c17c61e9-4355-4434-bc0a-46c66252d20a)

All of my code is within the blue folder, the rest is odoo sources and config files.

**Comment by trinhanhngoc** [comment] 2024-08-19 14:16
@PierrePasq ,

Thanks for the additional info. I can reproduce the problem. This will be fixed in the next version this week.

**Comment by PierrePasq** [comment] 2024-08-19 14:17
Thanks a lot :)

**Comment by PierrePasq** [comment] 2024-09-04 14:17
Did you find how to fix the issue? I still have this problem and can't find a good temporary fix.

**Comment by trinhanhngoc** [comment] 2024-09-04 14:48
@PierrePasq ,

Yes. The new release is delayed a bit due to an important refactoring. I will try to release it this week. Sorry for the delay.

**Comment by trinhanhngoc** [comment] 2024-09-11 03:32
Hello @PierrePasq ,

The new version 2024.7.0 has been released with the fix for this issue.

**Closed as completed by trinhanhngoc** 2024-09-11 03:32 UTC
Labels: bug, addressed in next version

**Comment by cbusillo** [comment] 2025-05-17 16:46
Can you check this issue for a regression?  On the latest PyCharm and Odoo plugin I seem to have directory names only when the Odoo plugin is enabled.

**Comment by trinhanhngoc** [comment] 2025-05-18 07:55
Hello @cbusillo ,

Thanks for the report. I just reproduced the regression. This will be fixed in the next version next week.

**Comment by cbusillo** [comment] 2025-05-18 15:51
Thanks!  I have to take the time every time I comment to mention how awesome your plugin is.  No way would I be as confident in Odoo without the type safety (along with all the neat things) your plugin does.

**Comment by trinhanhngoc** [comment] 2025-05-27 03:30
Hello @cbusillo,

The new version 2025.4.0 has been released to fix this issue.
